baseURL = "https://johndoe.dev"
languageCode = 'en-us'
title = 'John Doe'
theme = 'hugo-noir'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "John Doe"
location = "Anytown, USA"
description = "AI Developer. ML Engineer. I finetune models, build scalable pipelines and automate workflows."
profile_image = "/images/profile.jpg"
discord = "johndoe123"
github = "https://github.com/johndoe123"
github_username = "johndoe123"
email = "johndoe@example.com"
twitter = "https://www.twitter.com/johndoe123"
twitter_username = "johndoe123"
medium = "https://www.medium.com/@johndoe123"
linkedin = "https://www.linkedin.com/in/johndoe123"
linkedin_username = "johndoe123"
instagram = "https://instagram.com/johndoe123"
leetcode = "https://leetcode.com/johndoe123"
leetcode_username = "johndoe123"
monkeytype = "https://monkeytype.com/profile/johndoe123"
monkeytype_username = "johndoe123"
kaggle = "https://www.kaggle.com/johndoe123"
kaggle_username = "johndoe123"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5